version: "3.8"
services:
  scanner:
    build: ..
    env_file: ../app/.env
    restart: always
    container_name: stock_scanner
    # 필요시 리소스 제한
    deploy:
      resources:
        limits:
          memory: 1G